// This file is auto-generated by @hey-api/openapi-ts

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const BranchConversationPayloadSchema = {
    properties: {
        until_message_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Until Message Id'
        }
    },
    type: 'object',
    title: 'BranchConversationPayload'
} as const;

export const ChatMessagePublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        conversation_id: {
            type: 'string',
            format: 'uuid',
            title: 'Conversation Id'
        },
        sender: {
            type: 'string',
            title: 'Sender'
        },
        content: {
            type: 'string',
            title: 'Content'
        },
        metadata_json: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Metadata Json'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'conversation_id', 'sender', 'content', 'metadata_json', 'created_at'],
    title: 'ChatMessagePublic'
} as const;

export const ChatRequestPayloadSchema = {
    properties: {
        conversation_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Conversation Id'
        },
        message: {
            type: 'string',
            title: 'Message'
        },
        model_name: {
            type: 'string',
            title: 'Model Name',
            default: 'gemini-2.0-flash-lite'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'ChatRequestPayload'
} as const;

export const ConversationPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['id', 'title', 'created_at', 'updated_at'],
    title: 'ConversationPublic'
} as const;

export const ConversationUpdatePayloadSchema = {
    properties: {
        title: {
            type: 'string',
            title: 'Title'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'ConversationUpdatePayload'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const ItemCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'ItemCreate'
} as const;

export const ItemPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['title', 'id', 'owner_id'],
    title: 'ItemPublic'
} as const;

export const ItemUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'ItemUpdate'
} as const;

export const ItemsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ItemPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ItemsPublic'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const PortfolioItemCreateSchema = {
    properties: {
        symbol: {
            type: 'string',
            maxLength: 50,
            minLength: 1,
            title: 'Symbol'
        },
        quantity: {
            type: 'number',
            exclusiveMinimum: 0,
            title: 'Quantity'
        },
        buy_price: {
            type: 'number',
            exclusiveMinimum: 0,
            title: 'Buy Price'
        },
        avg_price: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Avg Price'
        },
        bought_at: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Bought At'
        }
    },
    type: 'object',
    required: ['symbol', 'quantity', 'buy_price'],
    title: 'PortfolioItemCreate'
} as const;

export const PortfolioItemPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        portfolio_id: {
            type: 'string',
            format: 'uuid',
            title: 'Portfolio Id'
        },
        symbol: {
            type: 'string',
            title: 'Symbol'
        },
        quantity: {
            type: 'number',
            title: 'Quantity'
        },
        buy_price: {
            type: 'number',
            title: 'Buy Price'
        },
        avg_price: {
            type: 'number',
            title: 'Avg Price'
        },
        bought_at: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Bought At'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'portfolio_id', 'symbol', 'quantity', 'buy_price', 'avg_price', 'bought_at', 'created_at'],
    title: 'PortfolioItemPublic'
} as const;

export const PortfolioMetricsPublicSchema = {
    properties: {
        total_invested: {
            type: 'number',
            title: 'Total Invested'
        },
        current_value: {
            type: 'number',
            title: 'Current Value'
        },
        total_return: {
            type: 'number',
            title: 'Total Return'
        },
        total_return_pct: {
            type: 'number',
            title: 'Total Return Pct'
        },
        cagr: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cagr'
        },
        sharpe_ratio: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sharpe Ratio'
        },
        sortino_ratio: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sortino Ratio'
        },
        beta: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Beta'
        },
        alpha: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Alpha'
        }
    },
    type: 'object',
    required: ['total_invested', 'current_value', 'total_return', 'total_return_pct', 'cagr', 'sharpe_ratio', 'sortino_ratio', 'beta', 'alpha'],
    title: 'PortfolioMetricsPublic'
} as const;

export const PortfolioPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        items: {
            items: {
                '$ref': '#/components/schemas/PortfolioItemPublic'
            },
            type: 'array',
            title: 'Items',
            default: []
        }
    },
    type: 'object',
    required: ['id', 'name', 'created_at'],
    title: 'PortfolioPublic'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const QuotaStatusPublicSchema = {
    properties: {
        standard_count: {
            type: 'integer',
            title: 'Standard Count',
            default: 0
        },
        standard_remaining_today: {
            type: 'integer',
            title: 'Standard Remaining Today'
        },
        standard_limit_today: {
            type: 'integer',
            title: 'Standard Limit Today',
            default: 10
        },
        upgraded_count: {
            type: 'integer',
            title: 'Upgraded Count',
            default: 0
        },
        upgraded_remaining_today: {
            type: 'integer',
            title: 'Upgraded Remaining Today'
        },
        upgraded_limit_today: {
            type: 'integer',
            title: 'Upgraded Limit Today',
            default: 3
        },
        seconds_until_next_allowed: {
            type: 'integer',
            title: 'Seconds Until Next Allowed',
            default: 0
        },
        is_limited: {
            type: 'boolean',
            title: 'Is Limited',
            default: false
        }
    },
    type: 'object',
    required: ['standard_remaining_today', 'upgraded_remaining_today'],
    title: 'QuotaStatusPublic'
} as const;

export const ResearchRequestPayloadSchema = {
    properties: {
        query: {
            type: 'string',
            title: 'Query'
        },
        model_name: {
            type: 'string',
            title: 'Model Name',
            default: 'gpt-5.6-luna'
        }
    },
    type: 'object',
    required: ['query'],
    title: 'ResearchRequestPayload',
    description: 'Request payload for research mode (4-analyst synthesis).'
} as const;

export const StockQuoteRequestSchema = {
    properties: {
        symbols: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Symbols'
        }
    },
    type: 'object',
    required: ['symbols'],
    title: 'StockQuoteRequest'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        },
        is_superuser: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Superuser'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;

export const WatchlistCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'WatchlistCreate'
} as const;

export const WatchlistItemCreateSchema = {
    properties: {
        symbol: {
            type: 'string',
            maxLength: 50,
            minLength: 1,
            title: 'Symbol'
        }
    },
    type: 'object',
    required: ['symbol'],
    title: 'WatchlistItemCreate'
} as const;

export const WatchlistItemPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        watchlist_id: {
            type: 'string',
            format: 'uuid',
            title: 'Watchlist Id'
        },
        symbol: {
            type: 'string',
            title: 'Symbol'
        },
        added_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Added At'
        }
    },
    type: 'object',
    required: ['id', 'watchlist_id', 'symbol', 'added_at'],
    title: 'WatchlistItemPublic'
} as const;

export const WatchlistPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        items: {
            items: {
                '$ref': '#/components/schemas/WatchlistItemPublic'
            },
            type: 'array',
            title: 'Items',
            default: []
        }
    },
    type: 'object',
    required: ['id', 'name', 'created_at'],
    title: 'WatchlistPublic'
} as const;