// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type BranchConversationPayload = {
    until_message_id?: (string | null);
};

export type ChatMessagePublic = {
    id: string;
    conversation_id: string;
    sender: string;
    content: string;
    metadata_json: (string | null);
    created_at: (string | null);
};

export type ChatRequestPayload = {
    conversation_id?: (string | null);
    message: string;
    model_name?: string;
};

export type ConversationPublic = {
    id: string;
    title: string;
    created_at: (string | null);
    updated_at: (string | null);
};

export type ConversationUpdatePayload = {
    title: string;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PortfolioItemCreate = {
    symbol: string;
    quantity: number;
    buy_price: number;
    avg_price?: (number | null);
    bought_at?: (string | null);
};

export type PortfolioItemPublic = {
    id: string;
    portfolio_id: string;
    symbol: string;
    quantity: number;
    buy_price: number;
    avg_price: number;
    bought_at: (string | null);
    created_at: (string | null);
};

export type PortfolioMetricsPublic = {
    total_invested: number;
    current_value: number;
    total_return: number;
    total_return_pct: number;
    cagr: (number | null);
    sharpe_ratio: (number | null);
    sortino_ratio: (number | null);
    beta: (number | null);
    alpha: (number | null);
};

export type PortfolioPublic = {
    id: string;
    name: string;
    created_at: (string | null);
    items?: Array<PortfolioItemPublic>;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type QuotaStatusPublic = {
    standard_count?: number;
    standard_remaining_today: number;
    standard_limit_today?: number;
    upgraded_count?: number;
    upgraded_remaining_today: number;
    upgraded_limit_today?: number;
    seconds_until_next_allowed?: number;
    is_limited?: boolean;
};

/**
 * Request payload for research mode (4-analyst synthesis).
 */
export type ResearchRequestPayload = {
    query: string;
    model_name?: string;
};

export type StockQuoteRequest = {
    symbols: Array<(string)>;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: (boolean | null);
    is_superuser?: (boolean | null);
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type WatchlistCreate = {
    name: string;
};

export type WatchlistItemCreate = {
    symbol: string;
};

export type WatchlistItemPublic = {
    id: string;
    watchlist_id: string;
    symbol: string;
    added_at: (string | null);
};

export type WatchlistPublic = {
    id: string;
    name: string;
    created_at: (string | null);
    items?: Array<WatchlistItemPublic>;
};

export type AgentGetQuotaStatusResponse = (QuotaStatusPublic);

export type AgentListConversationsResponse = (Array<ConversationPublic>);

export type AgentListConversationMessagesData = {
    conversationId: string;
};

export type AgentListConversationMessagesResponse = (Array<ChatMessagePublic>);

export type AgentUpdateConversationTitleData = {
    conversationId: string;
    requestBody: ConversationUpdatePayload;
};

export type AgentUpdateConversationTitleResponse = (ConversationPublic);

export type AgentDeleteConversationData = {
    conversationId: string;
};

export type AgentDeleteConversationResponse = (unknown);

export type AgentBranchConversationData = {
    conversationId: string;
    requestBody: BranchConversationPayload;
};

export type AgentBranchConversationResponse = (unknown);

export type AgentChatStreamData = {
    requestBody: ChatRequestPayload;
};

export type AgentChatStreamResponse = (unknown);

export type AgentOptionsChatStreamResponse = (unknown);

export type AgentResearchStreamData = {
    requestBody: ResearchRequestPayload;
};

export type AgentResearchStreamResponse = (unknown);

export type AgentOptionsResearchStreamResponse = (unknown);

export type ServeSpaData = {
    fullPath: string;
};

export type ServeSpaResponse = (unknown);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PortfoliosListPortfoliosResponse = (Array<PortfolioPublic>);

export type PortfoliosAddPortfolioItemData = {
    portfolioId: string;
    requestBody: PortfolioItemCreate;
};

export type PortfoliosAddPortfolioItemResponse = (PortfolioItemPublic);

export type PortfoliosDeletePortfolioItemData = {
    itemId: string;
    portfolioId: string;
};

export type PortfoliosDeletePortfolioItemResponse = (unknown);

export type PortfoliosUpdatePortfolioItemData = {
    itemId: string;
    portfolioId: string;
    requestBody: PortfolioItemCreate;
};

export type PortfoliosUpdatePortfolioItemResponse = (PortfolioItemPublic);

export type PortfoliosGetPortfolioMetricsData = {
    portfolioId: string;
};

export type PortfoliosGetPortfolioMetricsResponse = (PortfolioMetricsPublic);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);

export type UtilsSearchStocksData = {
    q: string;
};

export type UtilsSearchStocksResponse = (unknown);

export type UtilsGetStockQuotesData = {
    requestBody: StockQuoteRequest;
};

export type UtilsGetStockQuotesResponse = (unknown);

export type WatchlistsListWatchlistsResponse = (Array<WatchlistPublic>);

export type WatchlistsCreateWatchlistData = {
    requestBody: WatchlistCreate;
};

export type WatchlistsCreateWatchlistResponse = (WatchlistPublic);

export type WatchlistsDeleteWatchlistData = {
    watchlistId: string;
};

export type WatchlistsDeleteWatchlistResponse = (unknown);

export type WatchlistsAddWatchlistItemData = {
    requestBody: WatchlistItemCreate;
    watchlistId: string;
};

export type WatchlistsAddWatchlistItemResponse = (WatchlistItemPublic);

export type WatchlistsDeleteWatchlistItemData = {
    itemId: string;
    watchlistId: string;
};

export type WatchlistsDeleteWatchlistItemResponse = (unknown);