"""Add organization mirror, RAG documents, and org scoping

Revision ID: 002_add_org_rbac_rag
Revises: 001_add_research_mode
Create Date: 2026-08-12 13:43:39.352877

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '002_add_org_rbac_rag'
down_revision = '001_add_research_mode'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('is_personal', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ragdocument',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('source_ref', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('node_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ragdocument_org_id'), 'ragdocument', ['org_id'], unique=False)
    op.create_index(op.f('ix_ragdocument_status'), 'ragdocument', ['status'], unique=False)
    # org_id is nullable: existing rows predate organizations and are backfilled
    # by the Clerk webhook sync, not by this migration.
    op.add_column('portfolio', sa.Column('org_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_portfolio_org_id'), 'portfolio', ['org_id'], unique=False)
    op.create_foreign_key(
        'fk_portfolio_org_id', 'portfolio', 'organization', ['org_id'], ['id'], ondelete='CASCADE'
    )
    op.add_column('researchreport', sa.Column('org_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('researchreport', sa.Column('conversation_id', sa.Uuid(), nullable=True))
    op.add_column('researchreport', sa.Column('message_id', sa.Uuid(), nullable=True))
    op.add_column('researchreport', sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    op.create_index(op.f('ix_researchreport_conversation_id'), 'researchreport', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_researchreport_org_id'), 'researchreport', ['org_id'], unique=False)
    op.create_foreign_key(
        'fk_researchreport_message_id', 'researchreport', 'chatmessage', ['message_id'], ['id'],
        ondelete='SET NULL',
    )
    op.create_foreign_key(
        'fk_researchreport_org_id', 'researchreport', 'organization', ['org_id'], ['id'],
        ondelete='CASCADE',
    )
    op.create_foreign_key(
        'fk_researchreport_conversation_id', 'researchreport', 'conversation', ['conversation_id'], ['id'],
        ondelete='SET NULL',
    )
    # created_by_model previously defaulted to a hardcoded model name at the
    # database level; the caller now supplies the real model per report.
    op.alter_column('researchreport', 'created_by_model', server_default=None)
    op.add_column('watchlist', sa.Column('org_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_watchlist_org_id'), 'watchlist', ['org_id'], unique=False)
    op.create_foreign_key(
        'fk_watchlist_org_id', 'watchlist', 'organization', ['org_id'], ['id'], ondelete='CASCADE'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_watchlist_org_id', 'watchlist', type_='foreignkey')
    op.drop_index(op.f('ix_watchlist_org_id'), table_name='watchlist')
    op.drop_column('watchlist', 'org_id')
    op.alter_column('researchreport', 'created_by_model', server_default='gpt-5.6-luna')
    op.drop_constraint('fk_researchreport_conversation_id', 'researchreport', type_='foreignkey')
    op.drop_constraint('fk_researchreport_org_id', 'researchreport', type_='foreignkey')
    op.drop_constraint('fk_researchreport_message_id', 'researchreport', type_='foreignkey')
    op.drop_index(op.f('ix_researchreport_org_id'), table_name='researchreport')
    op.drop_index(op.f('ix_researchreport_conversation_id'), table_name='researchreport')
    op.drop_column('researchreport', 'title')
    op.drop_column('researchreport', 'message_id')
    op.drop_column('researchreport', 'conversation_id')
    op.drop_column('researchreport', 'org_id')
    op.drop_constraint('fk_portfolio_org_id', 'portfolio', type_='foreignkey')
    op.drop_index(op.f('ix_portfolio_org_id'), table_name='portfolio')
    op.drop_column('portfolio', 'org_id')
    op.drop_index(op.f('ix_ragdocument_status'), table_name='ragdocument')
    op.drop_index(op.f('ix_ragdocument_org_id'), table_name='ragdocument')
    op.drop_table('ragdocument')
    op.drop_table('organization')
    # ### end Alembic commands ###
