"""Add clerk_user_id, make hashed_password nullable

Revision ID: 003_add_clerk_user_id
Revises: 002_add_org_rbac_rag
Create Date: 2026-08-12 15:49:29.782151

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '003_add_clerk_user_id'
down_revision = '002_add_org_rbac_rag'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('clerk_user_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_user_clerk_user_id'), 'user', ['clerk_user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_clerk_user_id'), table_name='user')
    # Clerk-provisioned users have no password hash, so restoring NOT NULL would
    # fail on them. Give them an unusable placeholder rather than blocking the
    # downgrade -- they can only authenticate via Clerk anyway.
    op.execute("UPDATE \"user\" SET hashed_password = '!' WHERE hashed_password IS NULL")
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('user', 'clerk_user_id')
    # ### end Alembic commands ###
