"""add_chart_data_to_research_report

Revision ID: 2f1ef8125f1b
Revises: 003_add_clerk_user_id
Create Date: 2026-08-12 17:14:21.829165

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2f1ef8125f1b'
down_revision = '003_add_clerk_user_id'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS org_research_idx_1")
    op.execute("DROP TABLE IF EXISTS data_org_research")
    op.add_column('researchreport', sa.Column('chart_data', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('researchreport', 'chart_data')
    op.create_table('data_org_research',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('metadata_', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('node_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('data_org_research_pkey'))
    )
    op.create_index(op.f('org_research_idx_1'), 'data_org_research', [sa.literal_column("(metadata_ ->> 'ref_doc_id'::text)")], unique=False)
    # ### end Alembic commands ###
