/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SetupOrganizationRouteImport } from './routes/setup-organization'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SsoCallbackRouteImport } from './routes/sso-callback'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutChatRouteImport } from './routes/_layout/chat'
import { Route as LayoutDashboardRouteImport } from './routes/_layout/dashboard'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutOrganizationRouteImport } from './routes/_layout/organization'
import { Route as LayoutPortfoliosRouteImport } from './routes/_layout/portfolios'
import { Route as LayoutResearchReportsRouteImport } from './routes/_layout/research-reports'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutWatchlistsRouteImport } from './routes/_layout/watchlists'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupOrganizationRoute = SetupOrganizationRouteImport.update({
  id: '/setup-organization',
  path: '/setup-organization',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SsoCallbackRoute = SsoCallbackRouteImport.update({
  id: '/sso-callback',
  path: '/sso-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutChatRoute = LayoutChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDashboardRoute = LayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOrganizationRoute = LayoutOrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPortfoliosRoute = LayoutPortfoliosRouteImport.update({
  id: '/portfolios',
  path: '/portfolios',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutResearchReportsRoute = LayoutResearchReportsRouteImport.update({
  id: '/research-reports',
  path: '/research-reports',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutWatchlistsRoute = LayoutWatchlistsRouteImport.update({
  id: '/watchlists',
  path: '/watchlists',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup-organization': typeof SetupOrganizationRoute
  '/signup': typeof SignupRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/admin': typeof LayoutAdminRoute
  '/chat': typeof LayoutChatRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/items': typeof LayoutItemsRoute
  '/organization': typeof LayoutOrganizationRoute
  '/portfolios': typeof LayoutPortfoliosRoute
  '/research-reports': typeof LayoutResearchReportsRoute
  '/settings': typeof LayoutSettingsRoute
  '/watchlists': typeof LayoutWatchlistsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup-organization': typeof SetupOrganizationRoute
  '/signup': typeof SignupRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/admin': typeof LayoutAdminRoute
  '/chat': typeof LayoutChatRoute
  '/dashboard': typeof LayoutDashboardRoute
  '/items': typeof LayoutItemsRoute
  '/organization': typeof LayoutOrganizationRoute
  '/portfolios': typeof LayoutPortfoliosRoute
  '/research-reports': typeof LayoutResearchReportsRoute
  '/settings': typeof LayoutSettingsRoute
  '/watchlists': typeof LayoutWatchlistsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup-organization': typeof SetupOrganizationRoute
  '/signup': typeof SignupRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/chat': typeof LayoutChatRoute
  '/_layout/dashboard': typeof LayoutDashboardRoute
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/organization': typeof LayoutOrganizationRoute
  '/_layout/portfolios': typeof LayoutPortfoliosRoute
  '/_layout/research-reports': typeof LayoutResearchReportsRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/watchlists': typeof LayoutWatchlistsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/setup-organization'
    | '/signup'
    | '/sso-callback'
    | '/admin'
    | '/chat'
    | '/dashboard'
    | '/items'
    | '/organization'
    | '/portfolios'
    | '/research-reports'
    | '/settings'
    | '/watchlists'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/setup-organization'
    | '/signup'
    | '/sso-callback'
    | '/admin'
    | '/chat'
    | '/dashboard'
    | '/items'
    | '/organization'
    | '/portfolios'
    | '/research-reports'
    | '/settings'
    | '/watchlists'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/setup-organization'
    | '/signup'
    | '/sso-callback'
    | '/_layout/admin'
    | '/_layout/chat'
    | '/_layout/dashboard'
    | '/_layout/items'
    | '/_layout/organization'
    | '/_layout/portfolios'
    | '/_layout/research-reports'
    | '/_layout/settings'
    | '/_layout/watchlists'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SetupOrganizationRoute: typeof SetupOrganizationRoute
  SignupRoute: typeof SignupRoute
  SsoCallbackRoute: typeof SsoCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup-organization': {
      id: '/setup-organization'
      path: '/setup-organization'
      fullPath: '/setup-organization'
      preLoaderRoute: typeof SetupOrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sso-callback': {
      id: '/sso-callback'
      path: '/sso-callback'
      fullPath: '/sso-callback'
      preLoaderRoute: typeof SsoCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/chat': {
      id: '/_layout/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof LayoutChatRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/dashboard': {
      id: '/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutDashboardRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/organization': {
      id: '/_layout/organization'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof LayoutOrganizationRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/portfolios': {
      id: '/_layout/portfolios'
      path: '/portfolios'
      fullPath: '/portfolios'
      preLoaderRoute: typeof LayoutPortfoliosRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/research-reports': {
      id: '/_layout/research-reports'
      path: '/research-reports'
      fullPath: '/research-reports'
      preLoaderRoute: typeof LayoutResearchReportsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/watchlists': {
      id: '/_layout/watchlists'
      path: '/watchlists'
      fullPath: '/watchlists'
      preLoaderRoute: typeof LayoutWatchlistsRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutChatRoute: typeof LayoutChatRoute
  LayoutDashboardRoute: typeof LayoutDashboardRoute
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutOrganizationRoute: typeof LayoutOrganizationRoute
  LayoutPortfoliosRoute: typeof LayoutPortfoliosRoute
  LayoutResearchReportsRoute: typeof LayoutResearchReportsRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutWatchlistsRoute: typeof LayoutWatchlistsRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutChatRoute: LayoutChatRoute,
  LayoutDashboardRoute: LayoutDashboardRoute,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutOrganizationRoute: LayoutOrganizationRoute,
  LayoutPortfoliosRoute: LayoutPortfoliosRoute,
  LayoutResearchReportsRoute: LayoutResearchReportsRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutWatchlistsRoute: LayoutWatchlistsRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SetupOrganizationRoute: SetupOrganizationRoute,
  SignupRoute: SignupRoute,
  SsoCallbackRoute: SsoCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
